=== nolem321/IAS-Base-OSS/IAS-ServiceManagerLib/xsd/smcfg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.invenireaude.org/sm/cfg" 
xmlns:tns="http://www.invenireaude.org/sm/cfg">

	<complexType name="ResourceGroupExe">
		<sequence>
			<element name="nice" type="integer" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="ResourceGroupExeSudo">
		<complexContent>
			<extension base="tns:ResourceGroupExe">
				<sequence>
					<element name="user" type="string" minOccurs="0" maxOccurs="1" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Variable">	     
	    <attribute name="name" type="string" use="required"/>
	    <attribute name="value" type="string" use="optional"/>
	</complexType>

	<complexType name="Environment">
	  <sequence>
	     <element name="vars" type="tns:Variable" minOccurs="0" maxOccurs="unbounded" />
	  </sequence>
	</complexType>
		
	<complexType name="ResourceGroup">
		<sequence>
			<element name="logDir"   type="string"               minOccurs="1" maxOccurs="1" />
			<element name="count"    type="integer"              minOccurs="1" maxOccurs="1" />
			<element name="exe"      type="tns:ResourceGroupExe" minOccurs="0" maxOccurs="1" />
			<element name="env"      type="tns:Environment"      minOccurs="0" maxOccurs="1" />
			<element name="restartInterval" type="integer"       minOccurs="0" maxOccurs="1" />
		</sequence>
		<attribute name="name" type="string" use="required" />
		<attribute name="default" type="boolean"/>
	</complexType>

	<complexType name="Command">
		<sequence>
			<element name="exe" type="string" minOccurs="1" maxOccurs="1" />
			<element name="args" type="string" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="GroupingAttribute">
		<attribute name="name" type="string" />
		<attribute name="value" type="string" />
	</complexType>

	<simpleType name="DesiredState">
		<restriction base="string">
			<enumeration value="Stopped" />
			<enumeration value="Started" />
		</restriction>
	</simpleType>

	<complexType name="Service">
		<sequence>			
			<element name="grpAttrs" type="tns:GroupingAttribute" minOccurs="0" maxOccurs="unbounded" />
			<element name="startCmd" type="tns:Command" minOccurs="1" maxOccurs="1" />
			<element name="stopCmd" type="tns:Command" minOccurs="0" maxOccurs="1" />			
			<element name="resGrp" type="string" minOccurs="1" maxOccurs="unbounded" />
			<!-- TODO retry -->
		</sequence>
		  <attribute name="name" type="string" use="required"/>
	</complexType>

	<complexType name="ServiceConfig">
		<sequence>
			<element name="services" type="tns:Service" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="DeploymentConfig">
		<sequence>
		    <element name="lckDir"    type="string"  minOccurs="1" maxOccurs="1" />
		    <element name="refreshMS" type="integer" minOccurs="1" maxOccurs="1" />
			<element name="resources" type="tns:ResourceGroup" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<element name="serviceConfig" type="tns:ServiceConfig" />
	<element name="deploymentConfig" type="tns:DeploymentConfig" />

</schema>

=== nolem321/IAS-Base-OSS/IAS-ServiceManagerExe/cfg/sm/SMDeployment.xml
<?xml version="1.0" encoding="ASCII"?>
<ns0:deploymentConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://www.invenireaude.org/sm/cfg"
	xsi:type="ns0:DeploymentConfig" xsi:schemaLocation="http://www.invenireaude.org/sm/cfg ../../xsd/smcfg.xsd">

	<lckDir>/var/tmp/sm</lckDir>

	<refreshMS>1000</refreshMS>

	<resources name="RGTEST1">
		<logDir>/var/tmp/sm/logs</logDir>
		<count>2</count>
		<exe xsi:type="ns0:ResourceGroupExeSudo">
			<user>alojzy</user>
		</exe>
	</resources>
	<resources name="RGTEST2">
		<logDir>/var/tmp/sm/logs</logDir>
		<count>6</count>
		<exe xsi:type="ns0:ResourceGroupExeSudo">
			<user>test</user>
		</exe>
	</resources>
	<resources name="RGTEST3">
		<logDir>/var/tmp/sm/logs</logDir>
		<count>6</count>
		<exe />
	</resources>
</ns0:deploymentConfig>

=== nolem321/IAS-Base-OSS/IAS-ServiceManagerExe/cfg/sm/SMServices.xml
<?xml version="1.0" encoding="ASCII"?>
<ns0:serviceConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ns0="http://www.invenireaude.org/sm/cfg" xsi:type="ns0:ServiceConfig"
	xsi:schemaLocation="http://www.invenireaude.org/sm/cfg ../../xsd/smcfg.xsd">
	<services name="flow1">
		<grpAttrs name="type" value="flow" />
		<grpAttrs name="group" value="testing" />
		<grpAttrs name="group" value="shadow" />
		<startCmd>
			<exe>cfg/bin/monitor_me.sh</exe>
			<args>arg1alfa</args>
			<args>arg2beta</args>
			<args>arg3beta</args>
			<args>arg4beta</args>
		</startCmd>
		<stopCmd>
			<exe>cfg/bin/stop_me.sh</exe>
		</stopCmd>		
		<resGrp>RGTEST2</resGrp>
		<resGrp>RGTEST3</resGrp>
	</services>
	<services name="flow2">
		<grpAttrs name="type" value="flow" />
		<grpAttrs name="group" value="testing" />
		<startCmd>
			<exe>cfg/bin/monitor_me.sh</exe>
			<args>arg1</args>
			<args>arg2</args>
			<args>shadow</args>
		</startCmd>
		<stopCmd>
			<exe>cfg/bin/stop_me.sh</exe>
		</stopCmd>		
		<resGrp>RGTEST2</resGrp>
		<resGrp>RGTEST1</resGrp>
	</services>
	<services name="flow3">
		<grpAttrs name="type" value="flow" />
		<grpAttrs name="group" value="production" />
		<startCmd>
			<exe>cfg/bin/monitor_me.sh</exe>
			<args>arg1alfa</args>
			<args>arg2beta</args>
		</startCmd>
		<stopCmd>
			<exe>cfg/bin/stop_me.sh</exe>
		</stopCmd>		
		<resGrp>RGTEST2</resGrp>
		<resGrp>RGTEST3</resGrp>
	</services>
	<services name="flower">
		<grpAttrs name="type" value="flow" />
		<grpAttrs name="group" value="animal" />
		<grpAttrs name="group" value="alfa" />
		<startCmd>
			<exe>cfg/bin/monitor_me.sh</exe>
			<args>arg1alfa</args>
			<args>arg2beta</args>
			<args>arg3beta</args>
			<args>arg4beta</args>
		</startCmd>
		<stopCmd>
			<exe>cfg/bin/stop_me.sh</exe>
		</stopCmd>		
		<resGrp>RGTEST2</resGrp>
		<resGrp>RGTEST3</resGrp>
	</services>
	<services name="animal">
		<grpAttrs name="type" value="flow" />
		<grpAttrs name="group" value="animal" />
		<grpAttrs name="group" value="beta" />
		<startCmd>
			<exe>cfg/bin/monitor_me.sh</exe>
			<args>arg1alfa</args>
			<args>arg2beta</args>
			<args>arg3beta</args>
			<args>arg4beta</args>
		</startCmd>
		<stopCmd>
			<exe>cfg/bin/stop_me.sh</exe>
		</stopCmd>		
		<resGrp>RGTEST2</resGrp>
		<resGrp>RGTEST3</resGrp>
	</services>
	<services name="issues">
		<grpAttrs name="type" value="flow" />
		<grpAttrs name="group" value="testing" />
		<grpAttrs name="group" value="issues" />
		<startCmd>
			<exe>cfg/bin/monitor_me.sh</exe>
			<args>ala</args>
			<args>ma</args>
			<args>kota</args>
			<args>notka</args>
		</startCmd>
		<stopCmd>
			<exe>cfg/bin/stop_me.sh</exe>
		</stopCmd>
		<resGrp>RGTEST3</resGrp>
		<resGrp>RGTEST2</resGrp>
	</services>
</ns0:serviceConfig>
